import step1 from "./../../assets/process/step1.svg";
import step2 from "./../../assets/process/step2.svg";
import step3 from "./../../assets/process/step3.svg";
import "./Process.css";
function Process() {
  return (
    <div className="process">
      <div className="process__container">
        <div className="process__item">
          <img src={step1} alt="" />
          <div className="process__title">Search</div>
          <div className="process__desc">
            Simply add a keyword or a term related to your business in the
            slogan maker search box. Wait for the magic to happen.
          </div>
        </div>
        <div className="process__item">
          <img src={step2} alt="" />
          <div className="process__title">Select</div>
          <div className="process__desc">
            Choose from thousands of options generated by the slogan maker that
            fit your needs.
          </div>
        </div>
        <div className="process__item">
          <img src={step3} alt="" />
          <div className="process__title">Stand out</div>
          <div className="process__desc">
            Congrats on your new slogan. It's time to win the world!
          </div>
        </div>
      </div>
    </div>
  );
}
export default Process;
